CREATE UNLOGGED TABLE RAPORTOINTI_CAS_CLIENT_SESSION (
    MAPPED_TICKET_ID VARCHAR PRIMARY KEY,
    RAPORTOINTI_SESSION_ID CHAR(36) NOT NULL UNIQUE,
    CONSTRAINT RAPORTOINTI_CAS_CLIENT_SESSION_FK FOREIGN KEY (RAPORTOINTI_SESSION_ID) REFERENCES RAPORTOINTI_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX RAPORTOINTI_CAS_CLIENT_SESSION_IX1 ON RAPORTOINTI_CAS_CLIENT_SESSION (MAPPED_TICKET_ID);
