package fi.oph.viestinvalitys.vastaanotto.security

object SecurityConstants {

  final val OPH_ORGANISAATIO_OID = "1.2.246.562.10.00000000001"

  final val SECURITY_ROOLI_PREFIX = "ROLE_"
  final val SECURITY_ROOLI_LAHETYS = "APP_VIESTINVALITYS_LAHETYS"
  final val SECURITY_ROOLI_KATSELU = "APP_VIESTINVALITYS_KATSELU"
  final val SECURITY_ROOLI_PAAKAYTTAJA = "APP_VIESTINVALITYS_OPH_PAAKAYTTAJA"
  final val SECURITY_ROOLI_LAHETYS_FULL = SECURITY_ROOLI_PREFIX + SECURITY_ROOLI_LAHETYS
  final val SECURITY_ROOLI_KATSELU_FULL = SECURITY_ROOLI_PREFIX + SECURITY_ROOLI_KATSELU
  final val SECURITY_ROOLI_PAAKAYTTAJA_FULL = SECURITY_ROOLI_PREFIX + SECURITY_ROOLI_PAAKAYTTAJA

  final val LAHETYS_ROLES = Set(SECURITY_ROOLI_LAHETYS_FULL, SECURITY_ROOLI_PAAKAYTTAJA_FULL)
  final val KATSELU_ROLES = Set(SECURITY_ROOLI_KATSELU_FULL, SECURITY_ROOLI_PAAKAYTTAJA_FULL)
}