cas.base=https://virkailija.untuvaopintopolku.fi/cas
host.virkailija=https://virkailija.untuvaopintopolku.fi
cas.service=https://virkailija.untuvaopintopolku.fi/viestinvalityspalvelu
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks