cas.base=https://virkailija.hahtuvaopintopolku.fi/cas
host.virkailija=https://virkailija.hahtuvaopintopolku.fi
cas.service=https://hahtuva.viestinvalitys.opintopolku.fi/raportointi
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks