cas.base=https://virkailija.opintopolku.fi/cas
host.virkailija=https://virkailija.opintopolku.fi
cas.service=https://virkailija.opintopolku.fi/viestinvalityspalvelu
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://prod.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://prod.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks