web.url.cas=https://virkailija.testiopintopolku.fi/cas
host.virkailija=https://virkailija.testiopintopolku.fi
cas-service.service=https://virkailija.testiopintopolku.fi/viestinvalityspalvelu
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://qa.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://qa.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks