services:
  localstack:
    container_name: "viestinvalitys-localstack"
    build:
      context: ./localstack
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  postgres:
    container_name: "viestinvalitys-postgres"
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: [ "postgres", "-c", "max_connections=200" ]
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U viestinvalityspalvelu" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=viestinvalityspalvelu
  test-postgres:
    container_name: "viestinvalitys-test-postgres"
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5433:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d viestinvalityspalvelu" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=viestinvalityspalvelu
  keycloak:
    container_name: "viestinvalitys-keycloak"
    build:
      context: ../../viestinvalitys-service/keycloak
      dockerfile: Dockerfile
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      - "../../viestinvalitys-service/keycloak/cas-virkailija-realm.json:/opt/keycloak/data/import/cas-virkailija-realm.json"
      - "../../viestinvalitys-service/keycloak/themes/dev-quicklogin:/opt/keycloak/themes/dev-quicklogin"
    command: [ "start-dev", "--import-realm", "--health-enabled=true" ]
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
