cas.base=http://localhost:8888/realms/cas-virkailija/protocol/cas
cas.service=http://localhost:3000
cas.key=viestinvalitys
raportointi.login-success-url=http://localhost:3000/raportointi
cas.cookie-secure=false

spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG

aws.region=us-east-1
aws.s3.endpoint=http://localhost:4566
aws.s3.path-style-access=true

attachments.bucket.name=local-viestinvalityspalvelu-attachments
